@LibraryManagement_HostAddress = http://localhost:5098


@accessToken= eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiemFyaS53ZWVrMiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Inphcmkud2VlazJAZXhhbXBsZS5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJVc2VyIiwianRpIjoiZjAxZWJkNWItOWE0NS00OGU3LWE1ZjItMzk3MWMzYmQwZjVjIiwiZXhwIjoxNzg1MTgwNjg5LCJpc3MiOiJMaWJyYXJ5TWFuYWdlbWVudC5BcGkiLCJhdWQiOiJMaWJyYXJ5TWFuYWdlbWVudC5DbGllbnQifQ.2NU4tTiFcBVHAA-pkrbhbqX3ajjwUDcD40PaGMqveKc
GET {{LibraryManagement_HostAddress}}/api/books?pageNumber=1&pageSize=10&sortBy=title&sortDirection=asc
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{LibraryManagement_HostAddress}}/api/authors?pageNumber=1&pageSize=10&sortBy=firstName&sortDirection=asc
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{LibraryManagement_HostAddress}}/api/members?pageNumber=1&pageSize=10&sortBy=firstName&sortDirection=asc
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{LibraryManagement_HostAddress}}/api/loans?pageNumber=1&pageSize=10&sortBy=dueDate&sortDirection=asc
Authorization: Bearer {{accessToken}}
Accept: application/json

###

POST {{LibraryManagement_HostAddress}}/api/books
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "title": "Role Test Book",
  "bookCode": "ROLE-USER-001",
  "publishedYear": 2026,
  "totalCopies": 1,
  "availableCopies": 1
}

###